version: "3"
services:
  aslant-mongo:
    image: "mongo"
    volumes:
      - $HOME/aslant-mongo:/data
  aslant-redis:
    image: "redis:alpine"
  aslant:
    build: .
    depends_on:
      - aslant-mongo
      - aslant-redis
    environment:
      - "NODE_ENV=production"
      - "MONGO=mongodb://aslant-mongo/aslant"
      - "REDIS=redis://aslant-redis/"
    ports:
      - "5018:5018"
